# DEVELOPMENT MODE

# willm-frontend/Dockerfile
FROM node:22

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Expose the development server port
EXPOSE 5173

# Command to run the development server
CMD ["npm", "run", "dev"]

# PRODUCTION MODE I GUESS

# # willm-frontend/Dockerfile
# FROM node:22

# # Set the working directory
# WORKDIR /usr/src/app

# # Copy package.json and install dependencies
# COPY package*.json ./
# RUN npm install

# # Copy the rest of the application code
# COPY . .

# # Build the Vue.js application
# RUN npm run build

# # Install serve to serve the build files
# RUN npm install -g serve

# # Expose the port serve runs on
# EXPOSE 5000

# # Command to serve the build files
# CMD ["serve", "-s", "dist"]