# willm-flask-api/Dockerfile
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Run the application with waitress
CMD ["waitress-serve", "--host:0.0.0.0", "--port=8000", "app:app"]
