services:
  flask-api:
    build:
      context: ./willm-flask-api
    ports:
      - "8000:8000"
    environment:
      - FLASK_API_KEY=${FLASK_API_KEY}

  nestjs:
    build:
      context: ./willm-backend
    ports:
      - "3000:3000"
    depends_on:
      - flask-api
      - mongodb

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
