<script setup>
import { computed } from 'vue';

const props = defineProps({
    reviewData: {
        type: [Object, String],
        default: () => null
    }
});

const getDisplayKey = (key) => {
    if (key === 'grammar_vocab') {
        return 'Grammar and Vocabulary';
    }
    return key.charAt(0).toUpperCase() + key.slice(1);
};

// Filter out keys with empty improvements and tips arrays
const filteredReviewData = computed(() => {
    if (typeof props.reviewData === 'string' || !props.reviewData) {
        return {};
    }

    let bla = Object.fromEntries(
        Object.entries(props.reviewData).map(([key, value]) => {
            // If tips array is empty, add "everything's fine"
            if (value.tips && value.tips.length === 0) {
                value.tips.push("everything's fine");
            }

            // If improvements array is empty, add "everything's fine"
            if (value.improvements && value.improvements.length === 0) {
                value.improvements.push("everything's fine");
            }

            if (value.tips) {
                // Check if tips contain any generated tips (i.e., real tips) aside from the "not generated" ones
                const hasGeneratedTips = value.tips.some(tip =>
                    tip !== 'organization_tip not generated' && tip !== 'coherence_tip not generated'
                );

                // If there are valid tips, remove "organization_tip not generated" and "coherence_tip not generated"
                if (hasGeneratedTips) {
                    value.tips = value.tips.filter(tip =>
                        tip !== 'organization_tip not generated' && tip !== 'coherence_tip not generated'
                    );
                } else {
                    // If there are no other tips besides the "not generated" ones, replace with "everything's fine"
                    const hasOnlyNotGeneratedTips = value.tips.every(tip =>
                        tip === 'organization_tip not generated' || tip === 'coherence_tip not generated'
                    );

                    if (hasOnlyNotGeneratedTips && value.tips.length > 0) {
                        value.tips = ["everything's fine"];
                    }
                }
            }

            return [key, value];
        }).filter(([key, value]) => {
            return (
                (value.improvements && value.improvements.length) ||
                (value.tips && value.tips.length) ||
                (value.frequencies && value.frequencies.length)
            );
        })
    );

    console.log(bla);
    return bla;
});
</script>

<template>
    <div class="container">
        <div class="d-flex align-items-center justify-content-center mb-3">
            <img class="info-icon me-2" src="/icons/icon-info-01.svg" data-bs-toggle="popover"
                data-bs-placement="bottom" data-bs-content='
                <h5>What are reviews?</h5>
                <ul>
                    <li>Reviews serve as reminders of your current writing challenges.</li>
                    <ul>
                        <li>Tips: A recap of your most frequent mistakes in each category.</li>
                        <li>Improvements: Areas where you improved your writing.</li>
                    </ul>
                    <li>If there is no recent review available:</li>
                    <ul>
                        <li>Click on "Review" to generate one.</li>
                        <li><b>Remember:</b></li>
                        <ul>
                            <li>A review is generated by using your last 5 submissions.</li>
                            <li>You need to have at least two sessions and one submitted text to generate a review. These are generated when you evaluate your writing. Only one is generated each day.</li>
                        </ul>
                    </ul>
                </ul>' />
            <h2 class="mb-0">Review</h2>
        </div>
        <div v-if="typeof props.reviewData === 'string'">
            <p>{{ props.reviewData }}</p>
        </div>
        <div v-else-if="Object.keys(filteredReviewData).length">
            <div v-if="Object.values(filteredReviewData).some(data => data.tips.length)">
                <h5>Tips</h5>
                <ul>
                    <li>Regarding your last 5 submissions, your most frequent errors are:</li>
                    <ul>
                        <li v-for="(categoryData, key) in filteredReviewData" :key="key">
                            <template v-if="categoryData.tips.length">
                                {{ getDisplayKey(key) }}
                                <ul>
                                    <li v-for="(tip, index) in categoryData.tips" :key="index">
                                        {{ tip }} <span v-if="categoryData.frequencies[index]"> (Frequency: {{
            categoryData.frequencies[index] }})</span>
                                    </li>
                                </ul>
                            </template>
                        </li>
                    </ul>
                </ul>
            </div>
            <div v-if="Object.values(filteredReviewData).some(data => data.improvements.length)">
                <h5>Improvements</h5>
                <ul>
                    <li>Regarding your last 10 submissions, you improved yourself by reducing the following types of
                        mistakes:</li>
                    <ul>
                        <li v-for="(categoryData, key) in filteredReviewData" :key="key">
                            <template v-if="categoryData.improvements.length">
                                {{ getDisplayKey(key) }}
                                <ul>
                                    <li v-for="(improvement, index) in categoryData.improvements" :key="index">
                                        {{ improvement }}
                                    </li>
                                </ul>
                            </template>
                        </li>
                    </ul>
                </ul>
            </div>
        </div>
        <div v-else>
            <p>No review data available.</p>
        </div>
    </div>
</template>

<style scoped>
.info-icon {
    width: 25px;
    height: 25px;
    cursor: pointer;
}
</style>
