<script setup>
import { computed } from 'vue';

const props = defineProps({
    reviewData: {
        type: [Object, String],
        default: () => null
    }
});

const getDisplayKey = (key) => {
    if (key === 'grammar_vocab') {
        return 'Grammar and Vocabulary';
    }
    return key.charAt(0).toUpperCase() + key.slice(1);
};

// Filter out keys with empty improvements and tips arrays
const filteredReviewData = computed(() => {
    if (typeof props.reviewData === 'string' || !props.reviewData) {
        return {};
    }
    return Object.fromEntries(
        Object.entries(props.reviewData).filter(([key, value]) => {
            return (value.improvements && value.improvements.length) || (value.tips && value.tips.length);
        })
    );
});
</script>

<template>
    <div class="container">
        <div class="d-flex align-items-center justify-content-center mb-3">
            <img class="info-icon me-2" src="/icons/icon-info-01.svg" data-bs-toggle="popover"
                data-bs-placement="bottom" data-bs-content='
                <h5>What are reviews?</h5>
                <ul>
                    <li>Reviews serve as reminders of your current writing challenges.</li>
                    <ul>
                        <li>Tips: A recap of your most frequent mistakes in each category.</li>
                        <li>Improvements: Areas where you improved your writing.</li>
                    </ul>
                    <li>If there is no recent review available:</li>
                    <ul>
                        <li>Click on "Review" to generate one.</li>
                        <li><b>Remember:</b></li>
                        <ul>
                            <li>A review is generated by using your last submissions.</li>
                            <li>You need to have at least two sessions and one submitted text to generate a review. These are generated when you evaluate your writing. Only one is generated each day.</li>
                        </ul>
                    </ul>
                </ul>' />
            <h2 class="mb-0">Review</h2>
        </div>
        <div v-if="typeof props.reviewData === 'string'">
            <p>{{ props.reviewData }}</p>
        </div>
        <div v-else-if="Object.keys(filteredReviewData).length">
            <div>
                <h5>Tips</h5>
                <ul>
                    <li>Your most frequent errors are:</li>
                    <ul>
                        <li v-for="(categoryData, key) in filteredReviewData" :key="key">
                            {{ getDisplayKey(key) }}
                            <ul>
                                <li v-for="(tip, index) in categoryData.tips" :key="index">{{ tip }}</li>
                            </ul>
                        </li>
                    </ul>
                </ul>
            </div>
            <div
                v-if="Object.keys(filteredReviewData).some(key => filteredReviewData[key].improvements && filteredReviewData[key].improvements.length)">
                <h5>Improvements</h5>
                <ul>
                    <li>You improved yourself by reducing the following types of mistakes:</li>
                    <ul>
                        <li v-for="(categoryData, key) in filteredReviewData" :key="key">
                            {{ getDisplayKey(key) }}
                            <ul>
                                <li v-for="(improvement, index) in categoryData.improvements" :key="index">{{
            improvement }}</li>
                            </ul>
                        </li>
                    </ul>
                </ul>
            </div>
        </div>
        <div v-else>
            <p>No review data available.</p>
        </div>
    </div>
</template>

<style scoped>
.info-icon {
    width: 25px;
    height: 25px;
    cursor: pointer;
}
</style>
