<script setup>
import { computed, ref } from 'vue';

const feedbackDiv = ref(null);
const isTipSelected = ref(true);
const hoveredCardIndex = ref(null);

// Define props
const props = defineProps({
    reviewData: {
        type: [Object, String],
        default: () => null
    }
});

// Define examples for each category
const examples = {
    "misspelling": "The researcher <s>recieved</s> received funding for the study.",
    "subject-verb agreement": "The results of the experiment <s>demonstrates</s> demonstrate a clear trend.",
    "tense consistency": "The paper discusses the findings and <s>concluded</s> concludes with recommendations.",
    "pronoun agreement": "Each participant was asked to provide <s>their</s> his/her response anonymously.",
    "incorrect use of articles": "The study focused on <s>a</s> an impact of climate change on agriculture.",
    "incorrect prepositions": "This phenomenon is explained <s>with</s> by the theory of relativity.",
    "inappropriate word choice": "The paper states a very <s>bad</s> weak correlation between the variables.",
    "redundancy": "The study's results <s>clearly show and demonstrate</s> clearly show a significant correlation.",
    "punctuation": "<s>The data supports this claim however further research is needed</s> The data supports this claim; however, further research is needed.",
    "irrelevant content": "The methodology section describes the history of the field, which does not directly contribute to explaining the methods used in this study.",
    "poor logical flow": "The results section mentions the implications of the findings before presenting the actual data and analysis.",
    "poor transitions": "<s>The experiment was successful. There were some challenges.</s> Although the experiment was successful, there were some challenges.",
    "repetitive information": "The introduction states the hypothesis. The hypothesis is restated in the same words later in the introduction.",
    "disorganized ideas": "The first paragraph introduces the topic, the second investigates the results, and the third explains the methods.",
    "poor paragraph structure": "The paragraph begins with a minor detail, includes an unrelated statistic in the middle, and ends with the main idea.",
    "formal tone missing": "<s>The data was kind of hard to analyze</s> The data was somewhat challenging to analyze.",
    "missing precision and clarity": "<s>The results were good</s> The results showed significant improvement.",
    "passive voice overuse": "<s>The experiment was conducted by the students</s> The students conducted the experiment."
};

// Handle switch toggle
const toggleSwitch = () => {
    isTipSelected.value = !isTipSelected.value;
};

// Get the data to display (tips or improvements based on the switch state)
const displayData = computed(() => {
    if (typeof props.reviewData === 'string' || !props.reviewData) {
        return [];
    }

    return Object.entries(props.reviewData).map(([key, value]) => ({
        key,
        title: key === 'grammar_vocab'
            ? 'Grammar and Vocabulary'
            : key === 'writingStyle'
                ? 'Writing Style'
                : key.charAt(0).toUpperCase() + key.slice(1),
        items: isTipSelected.value ? value.tips : value.improvements,
    })).filter(entry => entry.items && entry.items.length);
});

// Get the example for a specific category
const getExample = (category) => {
    console.log("Received category:", category);
    if (!category) {
        return '';
    }

    const lowerCategory = category.toLowerCase();
    const example = examples[lowerCategory];
    if (example) {
        return "Example: " + example;
    }

    return "No example available";
};
</script>

<template>
    <div class="container">
        <div class="d-flex align-items-center justify-content-center mb-3">
            <img class="info-icon me-2" src="/icons/icon-info-01.svg" data-bs-toggle="popover"
                data-bs-placement="bottom" data-bs-content='
                <h5>What are reviews?</h5>
                <ul>
                    <li>Reviews serve as reminders of your current writing challenges.</li>
                    <ul>
                        <li>Tips: Shows most frequent mistake in each writing element.</li>
                        <li>Improvements: Areas where you improved your writing.</li>
                    </ul>
                    <li>If there is no recent review available:</li>
                    <ul>
                        <li>Click on "Review" to generate one.</li>
                        <li><b>Remember:</b></li>
                        <ul>
                            <li>A review is generated by using your last 5 submissions.</li>
                            <li>You need to have at least two sessions and one submitted text to generate a review. These are generated when you evaluate your writing. Only one is generated each day.</li>
                        </ul>
                    </ul>
                </ul>' />
            <h2 class="mb-0">Review</h2>
        </div>
        <div class="d-flex align-items-center justify-content-center mb-3">
            <div class="form-check form-switch d-flex align-items-center">
                <label class="form-check-label me-auto" for="reviewSwitch">Tips</label>
                <input class="form-check-input mx-2" type="checkbox" role="switch" id="reviewSwitch"
                    @change="toggleSwitch" :checked="!isTipSelected" />
                <label class="form-check-label ms-auto" for="reviewSwitch">Recent Improvements</label>
            </div>
        </div>
        <div class="feedback overflow-auto" ref="feedbackDiv">
            <div v-if="typeof props.reviewData === 'string'" class="text-center">
                <p>{{ props.reviewData }}</p>
            </div>
            <div v-else-if="displayData.length">
                <div v-for="(entry, index) in displayData" :key="index"
                    class="card mb-3 p-1 position-relative transition-all" @mouseenter="hoveredCardIndex = index"
                    @mouseleave="hoveredCardIndex = null">
                    <div
                        class="card-body text-center d-flex flex-column align-items-center justify-content-center h-100">
                        <h6 class="card-title fw-bold">{{ entry.title }}</h6>
                        <div v-if="hoveredCardIndex !== index" class="fade-transition">
                            <ul class="list-unstyled m-0">
                                <li v-for="(item, idx) in entry.items" :key="idx">
                                    {{ item.charAt(0).toUpperCase() + item.slice(1) }}
                                </li>
                            </ul>
                        </div>
                        <div v-else class="fade-transition">
                            <ul class="list-unstyled m-0">
                                <li v-for="(item, idx) in entry.items" :key="idx">
                                    <span v-html="getExample(item)"></span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div v-else class="text-center">
                <p>No data available.</p>
            </div>
        </div>
    </div>
</template>

<style scoped>
.info-icon {
    width: 25px;
    height: 25px;
    cursor: pointer;
}

.feedback {
    overflow-y: auto;
    max-height: 70vh;
    box-shadow: none;
    transition: box-shadow 0.3s ease-in-out;
}

.card {
    border: 1px solid #ddd;
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s ease-in-out, opacity 0.3s ease-in-out;
}

.fade-transition {
    transition: opacity 0.3s ease-in-out;
}

.card-title {
    font-weight: bold;
}

.card-text li {
    list-style: none;
    margin-left: 20px;
}

.card-text ul {
    list-style: none;
    padding-left: 0;
    margin-left: 0;
}

.form-check-input {
    cursor: pointer;
    color: #eabc7c;
}
</style>
